mindmap
    root((Normalization))
        def)Definition(
        anomalies[Anomalies]
            ins{{Insertion anomaly}}
                table
            upd{{Update anomaly}}
                table
            del{{Deletion anomaly}}
                table
        1nf(1st Normal Form)
            1nfReq)requirements(
            table
        2nf(2nd Normal Form)
            2nfReq)requirements(
            table
        3nf(3rd Normal Form)
            3nfReq)requirements(
            table
