gitGraph
    commit id: "Initial commit"
    branch develop
    checkout main
    commit
    checkout develop
    commit
    checkout main
    commit
    checkout develop
    commit id: "Important commit"
    checkout main
    commit
    checkout develop
    commit
    checkout main
    cherry-pick id: "Important commit"
    commit
