%%{init: {'gitGraph': {'mainBranchName': 'master'}} }%%
gitGraph
    commit id: "Initial commit"
    branch develop
    checkout master
    commit
    checkout develop
    commit
    checkout master
    commit
    checkout develop
    commit id: "Important commit"
    checkout master
    commit
    checkout develop
    commit
    checkout master
    cherry-pick id: "Important commit"
    commit
