%%{init: {'gitGraph': {'mainBranchName': 'master'}} }%%
gitGraph
    commit id: "Initial commit"
    branch feature/issue53
    branch feature/issue54
    checkout feature/issue53
    commit
    commit
    checkout master
    merge feature/issue53
    checkout feature/issue54
    commit
    checkout master
    commit
    merge feature/issue54 type:NORMAL id: "merge commit"