%%{init: {'gitGraph': {'mainBranchName': 'master'}} }%%
gitGraph
    commit id: "Initial commit"
    branch feature
    checkout master
    commit id: "Second commit"
    checkout feature
    commit id: "1st commit on feature"
    commit id: "2nd commit on feature"