%%{init: {'gitGraph': {'mainBranchName': 'master'}} }%%
gitGraph
    commit id: "Initial commit"
    branch feature
    checkout master
    commit
    commit
    checkout feature
    commit
    commit