gitGraph:
    commit id: "Initial commit"
    commit id: "383a7630" type: HIGHLIGHT
    branch develop
    commit id: "1fe791ec"
    branch testing
    commit id: "01cda149"
    checkout main
    commit id: "1c060f79"
